# Generated by Django 5.2.14 on 2026-06-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiRawDataJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.JSONField(help_text='AI가 생성한 정제 JSON 원본 통째로 저장')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_raw_data_json',
            },
        ),
        migrations.CreateModel(
            name='HairAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('face_shape', models.CharField(db_index=True, max_length=50)),
                ('style_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hair_analysis_log',
            },
        ),
    ]
