# Generated by Django 5.2.14 on 2026-06-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hairanalysislog",
            name="style_type",
            field=models.CharField(
                choices=[("recommended", "추천"), ("worst", "비추천")],
                db_index=True,
                default="recommended",
                max_length=20,
            ),
        ),
    ]
