# Generated by Django 5.2.14 on 2026-06-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_hairanalysislog_style_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairanalysislog',
            name='face_proportion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
