# Generated by Django 5.2.14 on 2026-06-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_hairanalysislog_face_proportion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairanalysislog',
            name='created_at',
        ),
    ]
