# Generated by Django 5.2.14 on 2026-06-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_remove_hairanalysislog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairStyle',
            fields=[
                ('style_code', models.CharField(help_text='스타일 고유 코드 (예: m-13)', max_length=20, primary_key=True, serialize=False)),
                ('style_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hair_styles',
            },
        ),
        migrations.CreateModel(
            name='FaceCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('face_shape', models.CharField(db_index=True, max_length=50)),
                ('face_proportion', models.CharField(blank=True, default='', max_length=50)),
                ('expert_reasoning_positive', models.TextField(blank=True, default='', help_text='긍정 피드백 분석')),
                ('expert_reasoning_negative', models.TextField(blank=True, default='', help_text='부정 피드백 분석')),
            ],
            options={
                'db_table': 'face_conditions',
                'unique_together': {('gender', 'face_shape', 'face_proportion')},
            },
        ),
        migrations.CreateModel(
            name='ConditionStyleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommended', models.BooleanField(db_index=True, default=True, help_text='True: 추천 스타일, False: 비추천 스타일')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_mappings', to='beauty.facecondition')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_mappings', to='beauty.hairstyle')),
            ],
            options={
                'db_table': 'condition_style_mapping',
                'unique_together': {('condition', 'style', 'is_recommended')},
            },
        ),
        migrations.CreateModel(
            name='StyleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_description', models.CharField(help_text='특징 설명 (예: 눈썹 아래 기장)', max_length=255)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='beauty.conditionstylemapping')),
            ],
            options={
                'db_table': 'style_features',
            },
        ),
    ]
