# Generated by Django 5.2.14 on 2026-06-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_remove_unique_together_add_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyle',
            name='style_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stylefeature',
            name='feature_description',
            field=models.CharField(max_length=255),
        ),
    ]
