# Generated by Django 5.2.14 on 2026-06-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beauty", "0007_alter_hairstyle_style_code_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HairAnalysisLog",
        ),
    ]
